function out1 = OdeBicycleModelLarge(Ts,in2)
%ODEBICYCLEMODELLARGE
%    OUT1 = ODEBICYCLEMODELLARGE(TS,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Jul-2021 11:29:02

df = in2(5,:);
dtheta = in2(4,:);
dy = in2(2,:);
theta = in2(3,:);
out1 = [dy;df.*8.380375e+1-dy.*1.005645e+1+theta.*1.676075e+2;dtheta;df.*7.343832407625962e+1-dtheta.*1.155331714367716e+1;dtheta];
