function out1 = OdeBicycleModelSmall(Ts,in2)
%ODEBICYCLEMODELSMALL
%    OUT1 = ODEBICYCLEMODELSMALL(TS,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-May-2021 11:32:00

df = in2(5,:);
dtheta = in2(4,:);
dy = in2(2,:);
theta = in2(3,:);
out1 = [dy;df.*(1.0e2./7.0)+dtheta.*(4.25e2./6.93e2)-dy.*1.443001443001443e1+theta.*(2.0e2./7.0);dtheta;df.*7.700653594771242e1-dtheta.*1.931919852115931e1+dy.*2.413019079685746e1-theta.*(4.3e2./9.0);dtheta];
