% soft constraints, lb <== Ax <== ub (OSQP format)
% slip <= slipMax
(-sin(deltaf)*(slipMax + 1))*xi{k}(1) + (-cos(deltaf)*(slipMax + 1))*xi{k}(2) + (params.w*cos(deltaf) - params.lf*sin(deltaf))*(slipMax + 1)*xi{k}(4) + params.rw*xi{k}(5) - e{k}(1) <= 0,...
(-sin(deltaf)*(slipMax + 1))*xi{k}(1) + (-cos(deltaf)*(slipMax + 1))*xi{k}(2) + (-(params.w*cos(deltaf) + params.lf*sin(deltaf))*(slipMax + 1))*xi{k}(4) + params.rw*xi{k}(6) - e{k}(2) <= 0,...
(- slipMax - 1)*xi{k}(2) + params.w*(slipMax + 1)*xi{k}(4) + params.rw*xi{k}(7) - e{k}(3) <= 0,...
(- slipMax - 1)*xi{k}(2) + (-params.w*(slipMax + 1))*xi{k}(4) + params.rw*xi{k}(8) - e{k}(4) <= 0,...
% slip > slipMin
sin(deltaf)*(slipMin + 1)*xi{k}(1) + cos(deltaf)*(slipMin + 1)*xi{k}(2) + (-(params.w*cos(deltaf) - params.lf*sin(deltaf))*(slipMin + 1))*xi{k}(4) + (-params.rw)*xi{k}(5) - e{k}(5) <= 0,...
sin(deltaf)*(slipMin + 1)*xi{k}(1) + cos(deltaf)*(slipMin + 1)*xi{k}(2) + (params.w*cos(deltaf) + params.lf*sin(deltaf))*(slipMin + 1)*xi{k}(4) + (-params.rw)*xi{k}(6) - e{k}(6) <= 0,...
(slipMin + 1)*xi{k}(2) + (-params.w*(slipMin + 1))*xi{k}(4) + (-params.rw)*xi{k}(7) - e{k}(7) <= 0,...
(slipMin + 1)*xi{k}(2) + params.w*(slipMin + 1)*xi{k}(4) + (-params.rw)*xi{k}(8) - e{k}(8) <= 0];
% slipAngle <= alphaMax
% collect([vxi{k}(5)y;vxi{k}(6)y;vxi{k}(7)y;vxi{k}(8)y] - alphaMax * [vxi{k}(5)x;vxi{k}(6)x;vxi{k}(7)x;vxi{k}(8)x] <= 0, xi)
(cos(deltaf) - alphaMax*sin(deltaf))*xi{k}(1) + (- sin(deltaf) - alphaMax*cos(deltaf))*xi{k}(2) + (alphaMax*(params.w*cos(deltaf) - params.lf*sin(deltaf)) + params.lf*cos(deltaf) + params.w*sin(deltaf))*xi{k}(4) - e{k}(9) <= 0,...
(cos(deltaf) - alphaMax*sin(deltaf))*xi{k}(1) + (- sin(deltaf) - alphaMax*cos(deltaf))*xi{k}(2) + (params.lf*cos(deltaf) - alphaMax*(params.w*cos(deltaf) + params.lf*sin(deltaf)) - params.w*sin(deltaf))*xi{k}(4) - e{k}(10) <= 0,...
xi{k}(1) + (-alphaMax)*xi{k}(2) + (alphaMax*params.w - params.lr)*xi{k}(4) - e{k}(11) <= 0,...
xi{k}(1) + (-alphaMax)*xi{k}(2) + (- params.lr - alphaMax*params.w)*xi{k}(4) - e{k}(12) <= 0,...
% slipAngle > alphaMin
% collect(-[vxi{k}(5)y;vxi{k}(6)y;vxi{k}(7)y;vxi{k}(8)y] + alphaMin * [vxi{k}(5)x;vxi{k}(6)x;vxi{k}(7)x;vxi{k}(8)x] <= 0, xi)
(alphaMin*sin(deltaf) - cos(deltaf))*xi{k}(1) + (sin(deltaf) + alphaMin*cos(deltaf))*xi{k}(2) + (- alphaMin*(params.w*cos(deltaf) - params.lf*sin(deltaf)) - params.lf*cos(deltaf) - params.w*sin(deltaf))*xi{k}(4) - e{k}(13) <= 0,...
(alphaMin*sin(deltaf) - cos(deltaf))*xi{k}(1) + (sin(deltaf) + alphaMin*cos(deltaf))*xi{k}(2) + (alphaMin*(params.w*cos(deltaf) + params.lf*sin(deltaf)) - params.lf*cos(deltaf) + params.w*sin(deltaf))*xi{k}(4) - e{k}(14) <= 0,...
alphaMin*xi{k}(2) - xi{k}(1) + (params.lr - alphaMin*params.w)*xi{k}(4) - e{k}(15) <= 0,...
alphaMin*xi{k}(2) - xi{k}(1) + (params.lr + alphaMin*params.w)*xi{k}(4) - e{k}(16) <= 0];