% soft constraints, lb <== Ax <== ub (OSQP format)
% slip <= slipMax
(-sin(deltaf)*(slipMax + 1))*vy + (-cos(deltaf)*(slipMax + 1))*vx + (w*cos(deltaf) - lf*sin(deltaf))*(slipMax + 1)*thetad + rw*wfl - eps1 <= 0,...
(-sin(deltaf)*(slipMax + 1))*vy + (-cos(deltaf)*(slipMax + 1))*vx + (-(w*cos(deltaf) + lf*sin(deltaf))*(slipMax + 1))*thetad + rw*wfr - eps2 <= 0,...
(- slipMax - 1)*vx + w*(slipMax + 1)*thetad + rw*wrl - eps3 <= 0,...
(- slipMax - 1)*vx + (-w*(slipMax + 1))*thetad + rw*wrr - eps4 <= 0,...
% slip > slipMin
sin(deltaf)*(slipMin + 1)*vy + cos(deltaf)*(slipMin + 1)*vx + (-(w*cos(deltaf) - lf*sin(deltaf))*(slipMin + 1))*thetad + (-rw)*wfl - eps5 <= 0,...
sin(deltaf)*(slipMin + 1)*vy + cos(deltaf)*(slipMin + 1)*vx + (w*cos(deltaf) + lf*sin(deltaf))*(slipMin + 1)*thetad + (-rw)*wfr - eps6 <= 0,...
(slipMin + 1)*vx + (-w*(slipMin + 1))*thetad + (-rw)*wrl - eps7 <= 0,...
(slipMin + 1)*vx + w*(slipMin + 1)*thetad + (-rw)*wrr - eps8 <= 0];
% slipAngle <= alphaMax
% collect([vwfly;vwfry;vwrly;vwrry] - alphaMax * [vwflx;vwfrx;vwrlx;vwrrx] <= 0, xi)
(cos(deltaf) - alphaMax*sin(deltaf))*vy + (- sin(deltaf) - alphaMax*cos(deltaf))*vx + (alphaMax*(w*cos(deltaf) - lf*sin(deltaf)) + lf*cos(deltaf) + w*sin(deltaf))*thetad - eps9 <= 0,...
(cos(deltaf) - alphaMax*sin(deltaf))*vy + (- sin(deltaf) - alphaMax*cos(deltaf))*vx + (lf*cos(deltaf) - alphaMax*(w*cos(deltaf) + lf*sin(deltaf)) - w*sin(deltaf))*thetad - eps10 <= 0,...
vy + (-alphaMax)*vx + (alphaMax*w - lr)*thetad - eps11 <= 0,...
vy + (-alphaMax)*vx + (- lr - alphaMax*w)*thetad - eps12 <= 0,...
% slipAngle > alphaMin
% collect(-[vwfly;vwfry;vwrly;vwrry] + alphaMin * [vwflx;vwfrx;vwrlx;vwrrx] <= 0, xi)
(alphaMin*sin(deltaf) - cos(deltaf))*vy + (sin(deltaf) + alphaMin*cos(deltaf))*vx + (- alphaMin*(w*cos(deltaf) - lf*sin(deltaf)) - lf*cos(deltaf) - w*sin(deltaf))*thetad - eps13 <= 0,...
(alphaMin*sin(deltaf) - cos(deltaf))*vy + (sin(deltaf) + alphaMin*cos(deltaf))*vx + (alphaMin*(w*cos(deltaf) + lf*sin(deltaf)) - lf*cos(deltaf) + w*sin(deltaf))*thetad - eps14 <= 0,...
alphaMin*vx - vy + (lr - alphaMin*w)*thetad - eps15 <= 0,...
alphaMin*vx - vy + (lr + alphaMin*w)*thetad - eps16 <= 0];